### ISSUE TITLE
How to build "libdht.so" in rpi code?

### ISSUE THREAD

**Issue by anhdenday** [PoJD/hawa#79]
Dear All, 

I am trying to read data from DHT sensor using rpi code from hawa project, but I am getting an error as following: 
`Unable to load the shared library dhtFile /home/pi/sitewhere-agent/libdht.so was not found in classpath.`
The absolute path of file libdht.so  is also "/home/pi/sitewhere-agent/libdht.so" but still error. I want to build this file on my raspberry pi again. How can I do? Please help me, thanks you so much

**Comment by PoJD** [comment]
Can you clarify what are you trying to do and what commands are you using?
